dist: trusty
sudo: false
language: php

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
php:
  - 7.0
  - 7.1
env:
  global:
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8888"
  matrix:
    - VERSION=HEAD

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - phpenv config-rm xdebug.ini
  - composer --version
  - phantomjs --version
  - composer global require "hirak/prestissimo:^0.3"

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash
  - composer install

  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'kickstart'@'localhost' IDENTIFIED BY 'kickstart'; GRANT ALL ON drupal.* TO 'kickstart'@'localhost';"

before_script:
  - php -S localhost:8888 -t ./web >& /dev/null &
  - phantomjs --ssl-protocol=any --ignore-ssl-errors=true $DRUPAL_TI_DRUPAL_DIR/vendor/jcalderonzumba/gastonjs/src/Client/main.js 8510 1024 768 2>&1 >> /dev/null &
  - ./bin/phing install -Ddb.database=drupal -Ddb.user=kickstart -Ddb.password=kickstart -Ddb.host=127.0.0.1 -Durl=$SIMPLETEST_BASE_URL

script:
  - composer validate ./web/profiles/commerce_kickstart/composer.json --no-check-all --ansi
  - ./bin/phing tests -Durl=http://127.0.0.1:8888

matrix:
  fast_finish: true
